SCHAUFEL_VERSION ?= 0.5

PREFIX ?= /usr/local
BINDIR ?= $(PREFIX)/bin
INSTALL_LIBDIR ?= $(PREFIX)/lib/schaufel
MANDIR ?= $(PREFIX)/share/man
MAN1DIR = $(MANDIR)/man1
MAN5DIR = $(MANDIR)/man5
DOCDIR ?= $(PREFIX)/share/doc/schaufel
INSTALL ?= install -D

CC ?= gcc
LD = $(CC)
CFLAGS += -Wall -Wextra -pedantic
CFLAGS += -std=c11
CFLAGS += -D_POSIX_C_SOURCE=200809L
CFLAGS += -D_SCHAUFEL_VERSION='"$(SCHAUFEL_VERSION)"'
CFLAGS += -D_BSD_SOURCE
CFLAGS += -D_LIBDIR=\"$(INSTALL_LIBDIR)\"
