#define INCLUDEDIR "/usr/local/include/schaufel"
#define LIBDIR "/usr/local/lib"
#define CONTRIBDIR "/usr/local/lib/schaufel"
#define DOCDIR "/usr/local/share/doc//schaufel"
#define MANDIR "/usr/local/share/man"
